; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
build_flags = 
	-std=gnu++17
	-I "include"
	; -D ENABLE_DEBUG
lib_deps = 
	SPI
	adafruit/Adafruit TCS34725@^1.4.4
	256dpi/MQTT @ ^2.5.2

[env:M5Stack_basic-ESPNOW-Repeater]
board = m5stack-core-esp32
build_flags = 
	${env.build_flags}
	-D M5STACK_BASIC
	-D ENABLE_DISPLAY
	-D ESPNOW
	-D REPEATER	
	-D ENABLE_DEBUG
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5Stack_basic-ESPNOW]
board = m5stack-core-esp32
build_flags = 
	${env.build_flags}
	-D M5STACK_BASIC
	-D ENABLE_DISPLAY
	-D ESPNOW
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:ATOM-MQTT-Color]
board = m5stack-atom
build_flags = 
	${env.build_flags}
	-D M5STACK_ATOM
	-D ENABLE_COLOR_SENSOR
	-D MQTT
	-D INTERNET
upload_speed = 1500000
lib_deps = 
	${env.lib_deps}
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.1.0
	fastled/FastLED@3.7.0
	m5stack/M5Unified@^0.2.2

[env:ATOM-MQTT_local-Color]
board = m5stack-atom
build_flags = 
	${env.build_flags}
	-D M5STACK_ATOM
	-D ENABLE_COLOR_SENSOR
	-D MQTT
	-D LOCAL
upload_speed = 1500000
lib_deps = 
	${env.lib_deps}
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.1.0
	fastled/FastLED@3.7.0
	m5stack/M5Unified@^0.2.2

; M5 Capsule
[env:M5Capsule-ESPNOW-AccelmImpact]
board = m5stack-stamps3
build_flags = 
	${env.build_flags}
	-D M5STAMP_S3
	-D ENABLE_ACCELOMETOR
	-D ESPNOW
	-D M5CAPSULE
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
	${env.lib_deps}
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.1.0
	fastled/FastLED@3.7.0
	sparkfun/SparkFun BMI270 Arduino Library @ ^1.0.3
	m5stack/M5Unified@^0.2.2

[env:M5Capsule-MQTT-Color]
board = m5stack-stamps3
build_flags = 
	${env.build_flags}
	-D M5STAMP_S3
	-D ENABLE_COLOR_SENSOR
	-D MQTT
	-D M5CAPSULE
lib_deps = 
	${env.lib_deps}
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.1.0
	fastled/FastLED@3.7.0
	m5stack/M5Unified@^0.2.2

[env:M5StackCoreS3-ESPNOW]
board = m5stack-cores3
build_flags = 
	${env.build_flags}
	-D M5STACK_CORE_S3
	-D ENABLE_DISPLAY
	-D ESPNOW
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5StampS3-ESPNOW]
board = m5stack-stamps3
build_flags = 
	${env.build_flags}
	-D M5STAMP_S3
	-D ESPNOW
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5Stick_C-ESPNOW]
board = m5stick-c
build_flags = 
	${env.build_flags}
	-D M5STICK_C
	-D ENABLE_DISPLAY
	-D ESPNOW
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5Stamp_C3-ESPNOW]
board = esp32-c3-devkitm-1
build_flags = 
	${env.build_flags}
	-D M5STAMP_C3_MATE
	-D ESPNOW
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2
