; Optional / rarely-used envs
; Enable by adding this line to platformio.ini:
;   [platformio]
;   extra_configs = platformio.optional.ini

[env:M5Stack_basic_RangeTest]
board = m5stack-core-esp32
build_flags = 
	${env.build_flags}
	-D M5STACK_BASIC
	-D ENABLE_DISPLAY
	-D ENABLE_TEST_DATA
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5StackCoreS3]
board = m5stack-cores3
build_flags = 
	${env.build_flags}
	-D M5STACK_CORE_S3
	-D ENABLE_DISPLAY
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5StampS3]
board = m5stack-stamps3
build_flags = 
	${env.build_flags}
	-D M5STAMP_S3
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5Stick_C]
board = m5stick-c
build_flags = 
	${env.build_flags}
	-D M5STICK_C
	-D ENABLE_DISPLAY
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5Stamp_C3]
board = esp32-c3-devkitm-1
build_flags = 
	${env.build_flags}
	-D M5STAMP_C3_MATE
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

[env:M5StickCPlus2_AccelTrigger]
board = m5stick-c
build_flags = 
	${env.build_flags}
	-D M5STICKC_PLUS2
	-D ENABLE_DISPLAY
	-D ENABLE_ACCEL_TRIGGER
lib_deps = 
	${env.lib_deps}
	m5stack/M5Unified@^0.2.2

